name: Push checks

on:
  push:
    branches:
      - master
      - beta

jobs:
  release:
    name: Release process
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
          scope: "@kuzzleio"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GHP }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          SEMANTIC_RELEASE_NPM_PUBLISH: "true"
          SEMANTIC_RELEASE_SLACK_WEBHOOK: ${{ secrets.SEMANTIC_RELEASE_SLACK_WEBHOOK }}
        run: npx semantic-release
