name: Run linter tests

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install nodejs version 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Lint project
        run: |
          npm install -g npm
          npm install
          npm run test:lint
